FROM maven:alpine

EXPOSE 8080 8081 8443 8444
COPY . /opt/app
WORKDIR /opt/app

RUN adduser -D app_user -h /home/app_user  \
 && chown -R app_user:app_user /opt/app
USER app_user

RUN mvn -DskipTests package

CMD [ "./start_app.sh" ]
